import 'dart:io';
import 'package:flutter/services.dart';
import 'package:intl/intl.dart';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import '../model/transaction_model.dart';

class ReportGeneratorService {
  Future<File> generatePdfReport({
    required List<TransactionModel> transactions,
    required String reportType,
    required double totalIncome,
    required double totalExpense,
    required double netWorth,
    required Map<String, double> categoryTotals,
  }) async {
    final pdf = pw.Document();

    final fontData = await rootBundle.load(
      "assets/fonts/static/NotoSansBengali-Regular.ttf",
    );
    final ttfRegular = pw.Font.ttf(fontData);

    pw.Font ttfBold;
    try {
      final boldFontData = await rootBundle.load(
        "assets/fonts/static/NotoSansBengali-Bold.ttf",
      );
      ttfBold = pw.Font.ttf(boldFontData);
    } catch (e) {
      ttfBold = ttfRegular;
    }

    final currencyFormat = NumberFormat('#,##0.00', 'en_US');

    final directory = await getTemporaryDirectory();
    final fileName =
        'Hisab_Report_${DateTime.now().millisecondsSinceEpoch}.pdf';
    final file = File('${directory.path}/$fileName');

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(40),
        theme: pw.ThemeData.withFont(base: ttfRegular, bold: ttfBold),
        build: (context) => [
          pw.Header(
            level: 0,
            child: pw.Text(
              'আর্থিক প্রতিবেদন / Financial Report',
              style: pw.TextStyle(
                fontSize: 22,
                fontWeight: pw.FontWeight.bold,
                font: ttfBold,
                color: PdfColors.teal800,
              ),
            ),
          ),
          pw.SizedBox(height: 10),
          pw.Paragraph(
            text: 'প্রতিবেদনের ধরন / Type: $reportType',
            style: pw.TextStyle(font: ttfRegular, fontSize: 12),
          ),
          pw.Paragraph(
            text:
                'তারিখ / Date: ${DateFormat('yyyy-MM-dd').format(DateTime.now())}',
            style: pw.TextStyle(font: ttfRegular, fontSize: 12),
          ),
          pw.Divider(),
          pw.SizedBox(height: 10),

          pw.Text(
            'সারসংক্ষেপ / Summary',
            style: pw.TextStyle(
              fontSize: 18,
              fontWeight: pw.FontWeight.bold,
              font: ttfBold,
            ),
          ),
          pw.SizedBox(height: 10),
          pw.Bullet(
            text:
                'মোট আয় / Total Income: BDT ${currencyFormat.format(totalIncome)}',
            style: pw.TextStyle(font: ttfRegular),
          ),
          pw.Bullet(
            text:
                'মোট ব্যয় / Total Expense: BDT ${currencyFormat.format(totalExpense)}',
            style: pw.TextStyle(font: ttfRegular),
          ),
          pw.Bullet(
            text:
                'নিট ব্যালেন্স / Net Balance: BDT ${currencyFormat.format(netWorth)}',
            style: pw.TextStyle(font: ttfRegular),
          ),

          pw.SizedBox(height: 25),
          pw.Text(
            'লেনদেন সমূহ / Transactions',
            style: pw.TextStyle(
              fontSize: 18,
              fontWeight: pw.FontWeight.bold,
              font: ttfBold,
            ),
          ),
          pw.SizedBox(height: 10),

          pw.TableHelper.fromTextArray(
            headerDecoration: const pw.BoxDecoration(color: PdfColors.grey300),
            headers: [
              'তারিখ (Date)',
              'বিভাগ (Category)',
              'ধরন (Type)',
              'পরিমাণ (Amount)',
            ],
            data: transactions
                .map(
                  (t) => [
                    DateFormat('yyyy-MM-dd').format(t.transactionDate),
                    t.category ?? 'অন্যান্য',
                    t.type == 'income' ? 'আয় (Income)' : 'ব্যয় (Expense)',
                    currencyFormat.format(t.amount),
                  ],
                )
                .toList(),
            headerStyle: pw.TextStyle(
              fontWeight: pw.FontWeight.bold,
              font: ttfBold,
            ),
            cellStyle: pw.TextStyle(font: ttfRegular),
            cellAlignment: pw.Alignment.centerLeft,
            headerAlignment: pw.Alignment.centerLeft,
          ),

          pw.Footer(
            margin: const pw.EdgeInsets.only(top: 20),
            trailing: pw.Text(
              'Generated by Hisab App',
              style: pw.TextStyle(
                fontSize: 10,
                color: PdfColors.grey,
                font: ttfRegular,
              ),
            ),
          ),
        ],
      ),
    );

    await file.writeAsBytes(await pdf.save());
    return file;
  }
}
